version: '3'
services:
  php:
    image: php:8.2-fpm
    volumes:
      - './src:/var/www/html'
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx/conf.d:/etc/nginx/conf.d'
  