version: '3.8'
services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html

  nginx-proxy:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - src:/var/www/html
      - prod/nginx:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - php
    networks:
      - net

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - src:/var/www/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - net

volumes:
  certs:
  src:
  vhost:
  acme:

networks:
  net:
    external: true